improve binding and add inital e2e tests (#8)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,17 +31,39 @@ jobs:
         uses: actions/cache@v3
         with:
           path: ~/.gradle/caches
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
           restore-keys: ${{ runner.os }}-gradle
       - name: Build & test
         run: |
           gradle wrapper
-          ./gradlew build check
-      - name: Bundle the build report
-        if: failure()
-        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
-      - name: Upload the build report
-        if: failure()
-        uses: actions/upload-artifact@v3
+          ./gradlew build check --stacktrace --info
+      - name: package
+        run: ./gradlew assemble --stacktrace  --info
+      - name: Run e2e tests
+        run: |
+          {
+           ./gradlew :wgpu4k-e2e:e2eTest --stacktrace --info || echo '::warning::Previous command failed'
+          } 2>&1 | sed 's/^::error::/::warning::/g'
+        continue-on-error: true
+
+      - name: Bundle chromium screenshot
+        uses: vimtor/action-zip@v1.2
         with:
-          path: build-reports.zip
+          files: ./wgpu4k-e2e/js-chromium/
+          recursive: false
+          dest: js-chromium-${{ runner.os }}-screenshots.zip
+
+      - name: Bundle jvm screenshot
+        uses: vimtor/action-zip@v1.2
+        with:
+          files: ./wgpu4k-e2e/jvm/
+          recursive: false
+          dest: jvm-${{ runner.os }}-screenshots.zip
+
+      - name: Upload the build reports
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ runner.os }}-artifacts
+          path: |
+            jvm-${{ runner.os }}-screenshots.zip
+            js-chromium-${{ runner.os }}-screenshots.zip
