Refactor e2e tests and add Maven configuration
Updated e2e tests structure and added detailed logging for screenshots. Introduced Maven configuration for Playwright driver and adjusted workflow to include fake X11 server and web driver installation for Ubuntu tests. Enabled `continue-on-error` for Ubuntu JVM e2e tests to ensure the workflow proceeds despite failures.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,6 +21,9 @@ jobs:
       - name: install dependencies
         if: matrix.os == 'ubuntu-latest'
         run: sudo apt install -y libglfw3-dev
+      - name: run fake X11 server
+        if: matrix.os == 'ubuntu-latest'
+        run: Xvfb :1 -screen 0 1024x768x16 &
       - name: set llvm Path On macos
         if: matrix.os == 'macos-14'
         run: echo "LIBCLANG_PATH=/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr" >> $GITHUB_ENV
@@ -53,7 +56,20 @@ jobs:
           ./gradlew fetch-native-dependencies build check --stacktrace
       - name: package
         run: ./gradlew assemble --stacktrace
-      - name: Run e2e tests
+      - name: Install web drivers
+        if: matrix.os == 'windows-latest'
+        run: mvn -B install -D skipTests --no-transfer-progress -f ./wgpu4k-e2e/pom.xml
+      - name: Run jvm e2e tests
+        if: matrix.os == 'ubuntu-latest'
+        run: |
+          {
+           ./gradlew :wgpu4k-e2e:e2eJvmTest --stacktrace --info || echo '::warning::Previous command failed'
+          } 2>&1 | sed 's/^::error::/::warning::/g'
+        continue-on-error: true
+        env:
+          DISPLAY: ":1"
+      - name: Run all e2e tests
+        if: matrix.os != 'ubuntu-latest'
         run: |
           {
            ./gradlew :wgpu4k-e2e:e2eTest --stacktrace --info || echo '::warning::Previous command failed'
